cask_args appdir: "/Applications"
tap "fisherman/tap"
brew "fish"
cask "java"
cask "docker"
brew "peco"
brew "fisherman"
cask "slack"
brew "hub"
brew "tig"
brew "direnv"
cask "google-backup-and-sync"
cask "raycast"