cask_args appdir: "/Applications"
tap "fisherman/tap"
brew "fish"
cask "java"
cask "docker"
cask "intellij-idea-ce"
brew "peco"
brew "fisherman"
cask "atom"
cask "slack"
brew "hub"
cask "iterm2"
brew "tig"
