[tools]
bat = "latest"
bun = "latest"
"cargo:tmux-shortcut-helper" = "latest"
chezmoi = "latest"
eza = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
go = "latest"
"go:github.com/satococoa/wtp/v2/cmd/wtp" = "latest"
lazygit = "latest"
neovim = "latest"
"npm:@devcontainers/cli" = "latest"
"npm:@openai/codex" = "latest"
peco = "latest"
rg = "latest"
rust = "latest"
starship = "latest"
tmux = "latest"
usage = "latest"
zellij = "latest"
zoxide = "latest"

[env]
MISE_NPM_PACKAGE_MANAGER = "bun"
